"""Change column name from skill to HYSYS in Itemr model

Revision ID: 4ab7151b4503
Revises: 89f5af3d3202
Create Date: 2023-07-11 10:40:46.546046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab7151b4503'
down_revision = '89f5af3d3202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('HYSYS', sa.String(), nullable=True))
    op.drop_index('ix_item_skills', table_name='item')
    op.create_index(op.f('ix_item_HYSYS'), 'item', ['HYSYS'], unique=False)
    op.drop_column('item', 'skills')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_item_HYSYS'), table_name='item')
    op.create_index('ix_item_skills', 'item', ['skills'], unique=False)
    op.drop_column('item', 'HYSYS')
    # ### end Alembic commands ###
